apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastio-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastio-deployment
  labels:
    app: elastio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastio
  template:
    metadata:
      labels:
        app: elastio
    spec:
      volumes:
        - name: elastio-volume
          persistentVolumeClaim:
            claimName: pg-pvc
      containers:
      - name: elastio
        image: elestio/pgadmin:latest
        volumeMounts:
        - mountPath: /pgadmin4/servers.json
          name: elastio-volume
          subPath: elastio
        resources:
          requests:
            cpu: "600m"
            memory: "512Mi"
          limits:
            cpu: "600m"
            memory: "512Mi"
        env:
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgadmin-secret
              key: PGADMIN_DEFAULT_PASSWORD
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            configMapKeyRef:
              name: pgadmin-configmap
              key: PGADMIN_DEFAULT_EMAIL
        - name: PGADMIN_LISTEN_PORT
          valueFrom:
            configMapKeyRef:
              name: pgadmin-configmap
              key: PGADMIN_LISTEN_PORT
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: elastio-service
spec:
  type: ClusterIP
  selector:
    app: elastio
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080